services:
  - type: web
    name: api-tarefas-backend
    env: node
    plan: free
    buildCommand: "npm --prefix backend install && npm --prefix backend run build"
    startCommand: "npm --prefix backend start"
    root: .
